version: '3'
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
  beat:
    build:
      context: .
      dockerfile: ./Dockerfile.beat
    volumes:
    - ./:/app/
    depends_on:
      - redis
  worker:
   build:
     context: .
     dockerfile: ./Dockerfile.worker
   volumes:
   - ./:/app/
   depends_on:
     - redis